### ISSUE TITLE
How to make it work with Microsoft 365 and modern authentication?

### ISSUE THREAD

**Issue by evmimagina** [camunda-community-hub/camunda-8-inbound-connector-email-watch#37]
Hi,

Basic authentication is no longer supported with Microsoft 365 services.... 

https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online#pop-imap-and-smtp-auth

therefore, when trying to configure the plugin to gather the emails from a Microsoft 365 IMAP account, doesn't work ... We've tried to create an App Password for basic authentication but it doesn't work either. 

As per thte article I've posted, the way to proceed when trying to access a mailbox from a Microsoft 365 (doesn't matter which protocol, POP3, IMAP)  is using the modern authentication mecanism, is it implemented in this camunda add-on? is there any plan to support it? 

Many thanks and best regards,

**Comment by superbeagle** [comment]
Hi,
     You can try using the officially supported Microsoft 365 connector from Camunda:
     
 https://docs.camunda.io/docs/components/connectors/out-of-the-box-connectors/microsoft-o365-mail/ 
 
 Which uses modern authentication methods. These could potentially be added to this community connector
